---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Identical code:
        enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
